default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: <%= ENV['DATABASE_DEV_HOST'] %>

development:
  <<: *default
  database: mine_share_development

test:
  <<: *default
  database: mine_share_test

production:
  <<: *default
  database: mine_share_production
  username: mine_share
  password: <%= ENV["MINE_SHARE_DATABASE_PASSWORD"] %>
